### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by silversquirl** [godot-zig/godot-zig#11]
The naming conventions in this project are a bit inconsistent, so I'd like to clarify what's intended.

1. The Zig convention for namespaces is `snake_case`, however this project seems to use mostly `TitleCase`. I'd like to propose switching to the Zig convention here, to match what Zig programmers are used to.
2. The Zig convention for function names is `camelCase`. The Godot convention is `snake_case`. This project uses a mix of both.
  I don't really have a strong preference about *which* style is chosen, but I think it's important to use a consistent style. Converting Godot's names to `camelCase` requires a bit of work in the binding generator, but it's not too bad. I think there's a strong case for matching Godot though, to make searching documentation easier.
3. Type names use `TitleCase` in Godot, Zig, and this library. No issues here :)

There are a few other issues, such as enum names, but most cases of those are currently in the C header that's `@cImport`ed by godot-zig, and dealing with that is beyond the scope of this issue.

**Comment by elvisxzhou** [comment]
Naming conventions are expected to be not 100% consistent since its cross language nature, but it for sure can get improved in many cases, so improvements are welcome, as long as following rules are respected:
1.  All names come from Godot should be kept as it is.
2. Other names, even those may be used in GDScript, should be in Zig convention.

**Comment by silversquirl** [comment]
1 seems reasonable, 2 feels a bit unexpected. For a user of this library, it's helpful to be able to predict the naming convention consistently, rather than having to know in advance whether some name comes from Godot, or is something this library adds as a helper function.

I would argue it's much more predictable to follow the Godot convention of `snake_case` for *all* function names, even those that don't come from Godot.

**Comment by elvisxzhou** [comment]
You made a good point here, let's make it clear.
Codes of a godot-zig project can be classified into three categories:
1. core godot stuff, including godot class names, method names, signal names etc, which are auto generated by bind_generator.
2. zig wrapper related, including Godot.zig, other extension classes and related.
3. pure zig codes, which may use names from 1&2, to implement non-godot logic.

then, 1&2 should follow Godot conventions while 3 follow Zig conventions.

**Comment by silversquirl** [comment]
To clarify, is category 3 just the binding generator, and example code?
That seems pretty reasonable to me :)

**Comment by elvisxzhou** [comment]
#3 includes codes like game framework, fsm, ecs etc.

**Comment by elvisxzhou** [comment]
I'm not working on this atm, PRs are welcome :)

**Comment by deevus** [comment]
I have had a stab at this in #41
