### ISSUE TITLE
Custom resources not working.

### ISSUE THREAD

**Issue by hazelnutcloud** [godot-zig/godot-zig#16]
Hi, I've been enjoying zig lately and was trying to refactor my [plugin](https://github.com/hazelnutcloud/godot-llama-cpp) from cpp to zig using this library but got blocked when trying to implement custom resources. Seems like there's two issues. I made a minimal reproduction build [here](https://github.com/hazelnutcloud/godot-zig/tree/buggy-resources)

1. First Issue is the implementing the `_load` function on the `ResourceFormatLoader` breaks when trying to use the full function signature. Using only one parameter however, works fine. [Relevant code](https://github.com/hazelnutcloud/godot-zig/blob/2256b4b9e07722c7b1a0de25b640b482044909dc/src/TestResourceFormatLoader.zig#L9). Here's the error output:
```
src/api/Godot.zig:351:39: error: struct 'String.String' has no member named 'callbacks_String'
                    const callbacks = @field(ObjectType, "callbacks_" ++ ObjectTypeName);
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
zig-cache/o/62ebacd7abb5b8a9af5ec83998c38cec/String.zig:9:27: note: struct declared here
pub const String = extern struct {
                   ~~~~~~~^~~~~~
referenced by:
    bind_ptrcall: src/api/Godot.zig:377:39
    _load: zig-cache/o/62ebacd7abb5b8a9af5ec83998c38cec/ResourceFormatLoader.zig:116:29
    get_virtual_ResourceFormatLoader__anon_43285: zig-cache/o/62ebacd7abb5b8a9af5ec83998c38cec/ResourceFormatLoader.zig:119:28
    get_virtual_bind: src/api/Godot.zig:290:32
    class_info: src/api/Godot.zig:156:37
    registerClass__anon_39040: src/api/Godot.zig:302:141
    initializeLevel: src/ExamplePlugin.zig:16:24
    my_extension_init: src/ExamplePlugin.zig:42:37
```

2. Second issue is that the path that's being passed into the `_load` function of a custom `ResourceFormatLoader` class seems to be empty. [Relevant code](https://github.com/hazelnutcloud/godot-zig/blob/2256b4b9e07722c7b1a0de25b640b482044909dc/src/TestCustomResource.zig#L12)

zig version: 0.12.0
godot version: 4.2.2

Btw awesome job on this library. Really excited to build with it!

**Comment by elvisxzhou** [comment]
wrong signature for _load,  should have self:*Self as first parameter, also String instead of *String is expected, you can check extension_api.json for reference. 
path in loadResource should be *const String as well.

**Comment by hazelnutcloud** [comment]
Ahh okay I'm just dumb. Thank you for taking your time to look at this 😅
