### ISSUE TITLE
Inheriting from a custom class

### ISSUE THREAD

**Issue by Zylann** [godot-zig/godot-zig#21]
### Question

How can I create a custom class inheriting another custom class [from the same project]?

I could not find any example of this in the examples. Inheriting from an engine class is pretty much this:

```zig
const CustomSprite = struct {
	pub usingnamespace Godot.Sprite2D;
	godot_object: *Godot.Sprite2D,
};
```

But I'm not sure how to go about exposing a class as being child of another custom one.

### Proposal

Unless I'm missing something obvious, here are my thoughts:

I've attempted to make my own WIP bindings by taking inspiration from yours, but could not see how you would handle this case. I ended up with the following idea, which however has some differences in how you did things:

```zig
const CustomSprite = struct {
	base: godot.Sprite2D,
	some_variable: i32,
	//...
};

const CustomDerivedSprite = struct {
	base: CustomSprite
	other_variable: i32,
	//...
};
```

The idea is that every subclass *contains* its parent with a field conventionally named `base`. `usingnamespace` cannot work here, because it only applies to non-instance members (like functions, constants, but not fields). Engine classes however can keep using `usingnamespace` because they don't have custom fields outside `godot_object` and it makes them easier to use.

Instead of directly getting `.godot_object`, Bindings can still lookup the `godot_object` when necessary by recursing `base` members with a comptime function:

```zig
// Note, might not compile, but it's just to illustrate the idea
pub fn getGodotObject(comptime TClass: type, obj: anytype) *TClass {
	if (@hasMember(obj, "godot_object")) {
		return obj.godot_object;
	}
	return getGodotOject(TClass, &obj.base);
}
```

### About `usingnamespace`

Something you might notice is how I removed `usingnamespace` in the base class too. The introduction of such `base` convention means there are two ways you could implement the "first" custom class: either you do it like now, or you do it with just `base: GodotClassOrCustomClass`. Both could work as a result of the bindings recognizing `base`. I like being able to do this, because I can decide whether I mix all Godot methods in my namespace or not. While before, I had no choice because that's how you accessed the API (or you had write the class name explicitely each time, while now you can just do `self.base.x()`).

However, classes deriving from the "first" custom class cannot use `usingnamespace` at all, because that would assume the inherited methods can use `self` to access their fields, which won't work because it's now behind `base.*`. I'm not aware of something in Zig allowing to bypass that to have actual field+methods "mixins".

That leads to some awkwardness if you have a deep inheritance tree and need to access fields or methods of a grand-grandparent:

```
self.base.base.base.some_variable = 42;
```

Which could be made clearer by using a comptime helper like this:

```zig
// Non-ambiguous, compile-time "upcast"
// Note, might not compile, but it's just to illustrate the idea
pub fn as(comptime TClass: type, obj: anytype) *TClass {
	if (@TypeOf(obj) == TClass) {
		return obj;
	}
	return as(TClass, &obj.base);
}

as(self, BaseClass).some_variable = 42;
```

### Polymorphism

Derived classes means polymorphism comes up.

What if you have an API that is exposed to Godot as taking `BaseCustomClass*`, and pass a `DerivedCustomClass*` to it?
Instance bindings would hold a pointer to the most derived one, but the Zig method has to receive a `BaseCustomClass*`. So once again, the `base` approach can work by having the method receive the address of the `base` field corresponding to `BaseCustomClass` somehow:

```zig
// In the wrapper calling the Zig method (pseudo-code)
obj_function(obj_self, &most_derived.base);
``` 

Casting would also work in a similar way:

```zig
// "downcast" which would return null on failure (same as in C++)
const derived_instance: DerivedCustomClass?* = godot.cast_to(DerivedCustomClass, base_instance);
```

I haven't gone to this point in my investigations, so I'm not sure what kind of wrinkles would be involved here.

I'm also aware of how you could do interfaces with vtables in pure Zig, and I have no idea yet how that would be put into place here. But I feel like it might make things a lot more complicated. Maybe this could be done in a way that is optional or up to the developer.

### Radical alternative

An opinionated alternative is to just not support this at all, on the principle that Zig doesn't really favor it, and that composition must be used instead. While that option might have good reasons in Zig land, and might not matter much if you make a game, that severely limits what can be exposed to Godot. I already restrict the use of inheritance in my own projects because I'm not a fan, I prefer using it in specific situations where it's actually useful. But half of my use cases for GDExtension is to make plugins, which are used by other people. Therefore, I often have to expose APIs making use of inheritance, and not being able to use it at all makes things harder.

**Comment by elvisxzhou** [comment]
I struggled with this also before, Zig does not and will never embrace OOP, I don't think supporting OOP is a good idea, though you may provide a solution in some tricky way, but finally the end user will face more challenges because of different philosophy behind. Composition is prefered way to go in Zig, otherwise why not use C++ in the first place?

**Comment by Zylann** [comment]
I've already been using C++ for a long time, and outside of Godot architectures I work with are essentially composed/ECS/interfaces-only/very shallow inheritance trees. I just started using Zig recently and I really like it, to the point I'd like to make my future projects in Zig instead of C++. But since a lot of my current projects involve Godot that's how I ended up trying to use Zig in Godot, which then involves OOP. So I thought I'd write down my investigation so far here.
I stopped my investigation for now, but if I find something later on I'll post it here.

**Comment by elvisxzhou** [comment]
Welcome aboard, though I miss features from D&Nim from time to time, I never miss any feature from C++ :) And Zig is by far very simple and powerful

**Comment by elvisxzhou** [comment]
get improved to some extent in 6aef5de0ece32f5b6e7a6f055a2ad38da268cd9d

**Comment by Zylann** [comment]
What was the changes? I see you added the concept of `base` instead of the `godot_object` pointer, but it doesn't seem to handle inheriting a custom class. I also havent seen yet what was the "callback stuff" in your bindings.

I've been thinking more about polymorphism and came to a point where I'm sort of re-implementing `dynamic_cast` in Zig. The main reason being mostly that it doesn't seem easy to set instance bindings to be a pointer to most-derived, because then it's unclear how to get a pointer to any base when that's what a function expects (i.e passing a *MyDerivedSprite to a function expecting *MyBaseSprite). Instance bindings are opaque, so since pointers to derived could point to anything, it's unsafe to cast. So instead instance bindings could be a pointer to the same known "bottom base" (i.e the address of the struct field containing the engine class binding). That base would then not just `godot_object`, but also a sort of ID or pointer that can be used to list all derived classes and their offsets relative to the base pointer. Then depending on which function is being called by Godot (i.e GDScript or whatever), the right offset can be picked, or an error can be produced if the caller actually sent the wrong object type. But that's mostly theory I've been thinking about, I still need to experiment that stuff eventually to see if that's what needs to happen or not.

**Comment by elvisxzhou** [comment]
I dont implement dynamic dispatching, you can check https://github.com/yglcode/zig_interfaces for reference
