### ISSUE TITLE
Custom `init` and `deinit`

### ISSUE THREAD

**Issue by Zylann** [godot-zig/godot-zig#23]
Is it possible for a custom class to have a recognized parameterless `init` function that would get called when the object is created? Just after `godot_object` is setup so that Godot APIs can be used in it?
If that's not already possible, maybe `godot.create` could call it if the class contains an `init` function; but it would have to also happen if the class is instantiated by GDScript or the scene loaded for example.
I could use `_ready` or `_enter_tree` in the meantime, but those functions only run when in the scene tree and don't even rexist on non-Node classes.

Correspondingly, would it be possible for a custom class to have a recognized `deinit` function, called just before the object is destroyed? (or should be a separate issue?)

**Comment by elvisxzhou** [comment]
I try to keep logic in node follow godot's conventions, those need a init are splitted into standalone pure zig modules.

**Comment by Zylann** [comment]
What do you mean? Every script language, modules and extensions have a way to do "constructor" and "destructor" logic. Do you mean these bindings somehow can't have that?

**Comment by elvisxzhou** [comment]
Yes you can have that and it's easy to add them, but I dont use godot as you described, I use it as a view layer of my game framework(similar to https://github.com/sschmid/Entitas/wiki/How-I-build-games-with-Entitas-%28FNGGames%29), that to say ,all godot nodes are created (loaded) from some kind of init functions, not vice versa.
