### ISSUE TITLE
Need Assistance with Binding Methods in Zig Godot Bindings for Gdscript

### ISSUE THREAD

**Issue by QEU-B-458** [godot-zig/godot-zig#32]
I am currently working with the Zig Godot bindings and need some help understanding how to bind a method in ClassDB for GDScript usage. In C++, this is done using the following line:

```
Copy code
ClassDB::bind_method(D_METHOD("get_speed"), &GDExample::get_speed);
```
Could someone please guide me on how to achieve this in Zig?
Any examples or detailed explanations would be greatly appreciated.
 Thank you in advance for your help!

**Comment by shiena** [comment]
You can bind by defining a `pub fn _bind_methods` function and calling `Godot.registerMethod` in it, as in this code.
https://github.com/godot-zig/godot-zig/pull/31

**Comment by QEU-B-458** [comment]
oh ty hmm we are unsure how to proceed the function we are providing doesn't need a func parameter so we are unsure what to put as type we are also new to zig

**Comment by shiena** [comment]
Can you provide the signature of the function you wish to bind?

**Comment by QEU-B-458** [comment]
```
pub fn log_help() void {
    log_helper.print("testing_method_bind", .{});
}
```

**Comment by shiena** [comment]
The first argument of a function to be bound must be the structure in which the function is defined.
Therefore, the following changes are required.

```zig
const Godot = @import("godot");
const Self = @This();

pub fn log_help(_: *Self) void {
    log_helper.print("testing_method_bind", .{});
}

pub fn _bind_methods() void {
    Godot.registerMethod(Self, "log_help");
}
```

**Comment by QEU-B-458** [comment]
oh thank you we understand better now
