### ISSUE TITLE
Exported properties examples?

### ISSUE THREAD

**Issue by tjpalmer** [godot-zig/godot-zig#4]
Hi! Thanks for the awesome work with these bindings!

I see the example signal connections like `Godot.connect(timer, "timeout", self, "onTimeout");` and the related machinery like `Godot.registerMethod`. I also see `_get_property_list`, but do you have any examples for this or helpers like for methods?

I'm trying to dig what I can on how to export properties, but there's a lot to dig through.

**Comment by elvisxzhou** [comment]
By now, you need to allocate an array of GDExtensionPropertyInfo, feed it with your data and return the address of the array in _get_property_list, also dont forget to assign the size of the array to r_count.(See wrapped.hpp:212 from godot-cpp)
Or, you can wait for me to improve this in next week when I find time.

**Comment by tjpalmer** [comment]
Thanks for the reply! I can be patient.

I also had trouble with emitting signals. [Signal registration works here](https://github.com/contextfreecode/gdext/blob/main/zig/src/ZigShip.zig) but not emitting.

I also finished my previous use case, which was [this video](https://youtu.be/c2TOIGcmQ7A). But if godot-zig and my code improve, I'll post a note to my channel at least to indicate the update.

**Comment by SlashScreen** [comment]
I can be patient too.

**Comment by elvisxzhou** [comment]
I've pushed a new commit to fix this, both property and signal work now. 
91a500e324d6079b62522be895605450ac924cdc
